# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

        # Configuración del servidor DNS Maestro
        config.vm.define :maestro do |maestro|
                maestro.vm.box = "bento/ubuntu-22.04"
                maestro.vm.network :private_network, ip: "192.168.50.4"
                maestro.vm.hostname = "maestro"
        end

        # Configuración del servidor DNS Esclavo
        config.vm.define :esclavo do |esclavo|
                esclavo.vm.box = "bento/ubuntu-22.04"
                esclavo.vm.network :private_network, ip: "192.168.50.5"
                esclavo.vm.hostname = "esclavo"
        end

        # Configuración del servidor Frontend
        config.vm.define :frontend do |frontend|
                frontend.vm.box = "bento/ubuntu-22.04"
                frontend.vm.network :private_network, ip: "192.168.50.3"
                frontend.vm.hostname = "frontend"
        end

       # Configuración del servidor Cliente
       config.vm.define :cliente do |cliente|
       cliente.vm.box = "bento/ubuntu-22.04"
       cliente.vm.network :private_network, ip: "192.168.50.2"
       cliente.vm.hostname = "cliente"
       end


end

